<<<<<<< HEAD
[project]
name = "auto-commit"
version = "0.1.0"
description = "Automate your git commits with ease."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
]
